### ISSUE TITLE
Pass UI into scheduleCommandParser

### ISSUE THREAD

**Issue by kumuwu** [CS2103-AY1819S1-T12-2/main#47]
As schedule command requires further input from user when parsing, I will need the UI to be passed into the Parser object. Instead of passing the entire Model, passing just the UI will be better to minimize coupling.

**Comment by shuiherng** [comment]
I think we should create a new window with a text command input and an output above it... This is for the following reasons:

- Logic is a dependency of Ui. If we passed in Ui to logic as well, then their dependency would be bidirectional, which isn't good.
- The keypresses to enter commands are registered through the Ui, and code which stores history of command input (as of now) cannot differentiate between commands and additional input for prompts
- Changing the input of new details to a new window will allow future expansions to add more information to the displayed window (for example, a calendar display).

The window will probably be instantiated by a `seedu.address.ui.PromptWindow<T>` class, where `T` denotes the type of object that will be returned by this window after the prompts are complete. This class will be instantiated from inside the command directly. We probably want a way to abort the command halfway, so the window should close upon `Esc` keypress, and return a `None`.

@lixinze777 For your consideration please.

**Comment by kumuwu** [comment]
I think it makes much more sense this way. I was worried about the idea of passing the entire UI into such a low level also.
Maybe instead of instantiating it in the command, what about instantiating in the Prompt class? When a Prompt object is instantiated, we automatically create a PromptWindow as well.

**Comment by shuiherng** [comment]
As discussed, `ScheduleCommandParser` will not extend interface `Parser`, but will be a standalone class.
The follow methods are being passed into ScheduleCommandParser's static method parse(String args, ScheduleModel scheduleModel)

**Comment by shuiherng** [comment]
#52
