### ISSUE TITLE
Request for review of code

### ISSUE THREAD

**Issue by ZZG229** [CS2103-AY1819S1-T12-2/main#65]
Hey Shui Herng, I just edited the list and find Command to include operations for diagnosis, may I have your attention for the following points please:

1. For the find command, instead of using the predicate, I just straightaway pass in a disease object newly instantiated in FindCommand class since predicate is used for a list of keywords. However, in my case, there is only one disease that needs to be checked, so I do not think that using predicate is necessary. You can check my pull request for the detailed implementation.

2. For list command, I understand that originally there was no need of parser for list command. However, because I am including list disease in the list command, so I added a private attribute called cmdType. Thus, now list command still needs to call listCommandParser(I created one) in PatientBookParser to differentiate what to list. 

3. For the execute() method in ListCommand, I tried to mimic what has been written in addCommand. However, I encounter a problem and I think it may be a potential bug. For list patient command, it simply just call addressBookModel.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS), the commandResult is just a success message. For list disease command, I included something like the one you wrote for addDisease part in addCommand, now it will return commandResult containing cmdResult = "Found the following disease:\n" + Arrays.toString(diseaseList). So I am not sure whether this can still work. Please help me revise the code and see if still can follow your implementation.

Thanks!

**Comment by shuiherng** [comment]
looks ok, I have actually changed the find command on my end, but it generally looks the same, I'll edit for the other parts where necessary. Thanks!
